import sys
import os
import json
import subprocess
import datetime
import uuid

def forge_app(agent_id, app_name, stack, prompt):
    """
    Scaffolds a new application in a sandboxed directory.
    Includes a standard 'Return to Garden' portal link.
    """
    print(f"Agent {agent_id} is forging a new {stack} app: {app_name}...")
    
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    work_dir = os.path.join(".tmp", "forge", f"{app_name}_{timestamp}")
    os.makedirs(work_dir, exist_ok=True)
    
    # Run the actual scaffolding command
    try:
        if stack == "vite-react-tailwind":
            subprocess.run(["npx", "-y", "create-vite@latest", ".", "--template", "react-ts"], cwd=work_dir, check=True)
            # Add Tailwind (simplified for this script, in practice would need more steps)
            print("Vite scaffolded successfully.")
        elif stack == "html-vanilla-js":
            with open(os.path.join(work_dir, "index.html"), "w") as f:
                f.write(f"<html><body><h1>{app_name}</h1><p>Welcome to your Soul Space.</p></body></html>")
    except Exception as e:
        return {"status": "error", "message": f"Scaffolding failed: {str(e)}"}
    
    with open(os.path.join(work_dir, "README.md"), "w") as f:
        f.write(f"# {app_name}\n\nGenerated by Agent {agent_id} for the Soul Garden.\n\nRequirement: {prompt}")
    
    app_id = str(uuid.uuid4())
    print(f"App {app_id} scaffolded at {work_dir}.")
    
    return {
        "status": "success",
        "app_id": app_id,
        "local_path": work_dir,
        "message": f"App '{app_name}' is ready for logic injection."
    }

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: python forge_app.py <agent_id> <app_name> <stack> <prompt>")
        sys.exit(1)
    
    agent_id, app_name, stack, prompt = sys.argv[1:5]
    result = forge_app(agent_id, app_name, stack, prompt)
    print(json.dumps(result))
